name: Release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
      id-token: write

    environment: release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 4.0.6
    - name: Configure trusted publishing credentials
      uses: rubygems/configure-rubygems-credentials@v2.1.0
    - name: Run release rake task
      run: bundle exec rake release
      shell: bash
    - name: Wait for release to propagate
      run: gem exec rubygems-await pkg/*.gem
      shell: bash
